#FROM maven:3.8.6 t
#COPY . .
#RUN mvn package -DskipTests
#
#FROM openjdk:21-jdk
#COPY --from=build /target/CampusNestProject-0.0.1-SNAPSHOT.jar CampusNest.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","CampusNestProject.jar"]
#
